### ISSUE TITLE
can nn-meter be used for pytorch/tensorflow on the server device?

### ISSUE THREAD

**Issue by g-crabapple** [microsoft/nn-Meter#106]
will there be the code guidence for custom backend for pytorch/tensorflow on the server device？because I had ever seen you say you test nn-meter on V100 in the answer under another issues.thanks

**Comment by JiahangXu** [comment]
Sorry for the late reply. As of now, we do not have plans to provide server-side guidance. In our preliminary experiments, we took a quick look at V100 inference and found that latency can be calculated through a lookup table, indicating that almost all operators run sequentially during inference. However, we have not conducted further exploration on this topic. In fact, backends on the server-side can be registered in the same way as on the edge-side, but it would require users to build their own interface.

**Comment by g-crabapple** [comment]
@JiahangXu thanks for your time! I'll try it
