### ISSUE TITLE
Used get_h to calculate outw...Is this a typo

### ISSUE THREAD

**Issue by YuqiData-UW** [microsoft/nn-Meter#112]
https://github.com/YuqiData-UW/nn-Meter/blob/4a00b043e7ad5ed37eb1946dc67b55107abdca75/nn_meter/ir_converter/frozenpb_converter/shape_inference.py#L153

Hi, could you explain why we use get_h to calculate outw? Or this is a typo?

**Comment by JiahangXu** [comment]
Yes I think its a typo! I will refine this. Thanks a lot!
