### ISSUE TITLE
About lower-level ir optimizatin detection

### ISSUE THREAD

**Issue by Kyrie-Zhao** [microsoft/nn-Meter#38]
I appreciate your efforts, nice work! Well, seems that nn-meter does not consider the tensor/code level optimization, while optimizations in this stage can make quite huge effects on run-time performance, especially for AI accelerators. Anyone interested in this topic? Will nn-meter extend the work to fully considerations of compiler level acceleration?

**Comment by Lynazhang** [comment]
Hi Kyrie, thanks for the interest and suggestion! Yep, nn-meter currently does not consider the compiler level optimizations. As we discussed in the paper (Discussion section), we will consider this kind of optimizations to further develop nn-meter. 
Very welcome to communicate about the compiler level accelerations!
