### ISSUE TITLE
datasets 中模型构建onnx无法通过infershape

### ISSUE THREAD

**Issue by Ein42** [microsoft/nn-Meter#42]
您好
       我尝试根据datasets当中Alexnet模型的参数生成为onnx，但是无法通过infershape的检测，我想了解下这些模型是如何实现测速的，是根据单个node的预测结果求和得到整个模型的速度吗？
![image](https://user-images.githubusercontent.com/51670324/140732375-841e5a0c-5473-4ca2-86ca-0a9a8de70ca4.png)

**Comment by Lynazhang** [comment]
Hi, 
目前dataset里模型的latency是我们通过生成tensorflow frozen pb/tflite模型，再在对应硬件上进行latency测量的。我们在公开数据集时，由于全部model的文件size太大，我们的处理是parse tensorflow pb, 并按照其node属性等保存成json文件。由于tensorflow和onnx模型保存格式不同，因此无法直接将datasets中模型的json string生成onnx。

如果需要onnx 模型测试，可先下载onnx_models.zip。

**Comment by JiahangXu** [comment]
Close the issue considering no further discussion. If you have other question, please feel free to create a new issue. 😃
