### ISSUE TITLE
Feature: will you add apple mlmodel support in the future?

### ISSUE THREAD

**Issue by HuaZheLei** [microsoft/nn-Meter#50]

**Comment by JiahangXu** [comment]
Thank you for your question. nn-Meter team has no plan to support Apple ML Model by now. However, nn-Meter building tool is going to be open source at the end of December in next release of nn-Meter package. Users could build latency predictors for their own device using nn-Meter building tool. I hope this tool will be of some help to you.

**Comment by HuaZheLei** [comment]
Cool!
