### ISSUE TITLE
I wonder if nn-Meter can be applied to other network structures?

### ISSUE THREAD

**Issue by nuts-bottles** [microsoft/nn-Meter#54]
I modify the original neural models in the code, but it returns 
"ValueError: Unsupported Model Name: modresnet50_0 in torchvision.
Supporting list: resnet18, alexnet, vgg16, squeezenet, densenet161, inception_v3, googlenet, shufflenet_v2, mobilenet_v2,  Resnext50_32x4d wide_resnet50_2, mnasnet"

**Comment by JiahangXu** [comment]
Hi, it seems you used nn-Meter with wrong `model_type`. We support latency prediction for CNN structure. If your model is CNN, you can refer to [this guidance](https://github.com/microsoft/nn-Meter/blob/main/docs/predictor/usage.md) to use nn-Meter. I think the python binding usage is more suitable in your case.

**Comment by nuts-bottles** [comment]
I find that there are some requirements for the definition of the model structure in NII model.
The code works well, thank you.
