### ISSUE TITLE
How to convert nn-Meter IR graph back to pb/onnx model?

### ISSUE THREAD

**Issue by XYAskWhy** [microsoft/nn-Meter#62]
Hi, I am very interested in the nn-Meter IR graph, but it seemed that we can only convert pb/onnx model to nn-Meter IR. Not opposite. Any plan on implementing a two-way IR? So that we can fully utilize the IR graphs in the benchmark datasets.

**Comment by JiahangXu** [comment]
Thank you for the advice! We have discussed about this. In future we could provide code to convert nn-Meter ir back to onnx file.

**Comment by SakuraiYuuta** [comment]
Does the code transfer ir graph back to onnx released?
