### ISSUE TITLE
Cannot open register_and_connect_backend.ipynb

### ISSUE THREAD

**Issue by Ramsonjehu** [microsoft/nn-Meter#68]
Hi,
I'm trying to create a new predictor for my edge device. The example notebook for register and connect backend (https://github.com/microsoft/nn-Meter/blob/main/examples/nn-meter_builder_examples/register_and_connect_backend.ipynb) is invalid.  

![image](https://user-images.githubusercontent.com/54444543/170954671-d7fae6de-3e4a-471f-a1e6-56581a9ad691.png)
The file size is also 0Kb. Please update the file. 

Thanks,
Ramson Jehu K

**Comment by JiahangXu** [comment]
Hi Ramson,
The notebook is empty, so I deleted the notebook in the current main branch. Considering all backend registration progress are done in command line, I think document is more helpful for backend registration. Please visit [docs](https://github.com/microsoft/nn-Meter/blob/main/docs/builder/prepare_backend.md#-build-customized-backend-) to get guidance of register backend. If you have any questions about backend registration, please feel free to let us know.
Thanks,
Jiahang
